// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var ctx, files, img, shuffle, win,
      _this = this;
    $("body").css("background", "#293134");
    $("#message").css("color", "#e0e2e4");
    $("#skip").on("click", function() {
      return win(true);
    });
    img = new Image();
    ctx = $("#area")[0].getContext("2d");
    win = function(skip) {
      if (skip == null) {
        skip = false;
      }
      $("#area").off("click");
      $("#area").hide();
      $("#skip").hide();
      return $("#message").text('Поздравляем, Вы прошли строжайший отбор и приглашены\nна день рождения Никиты!');
    };
    shuffle = function() {
      var i, j, order_pass, r, sum, _i, _j, _ref;
      order_pass = false;
      while (!order_pass) {
        r = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14].map(function(i) {
          return [i, Math.random()];
        }).sort(function(a, b) {
          return a[1] - b[1];
        }).map(function(a) {
          return a[0];
        });
        sum = 0;
        for (i = _i = 0; _i <= 13; i = ++_i) {
          for (j = _j = _ref = i + 1; _ref <= 14 ? _j <= 14 : _j >= 14; j = _ref <= 14 ? ++_j : --_j) {
            if (r[j] < r[i]) {
              sum = sum + 1;
            }
          }
        }
        order_pass = sum % 2 === 0;
      }
      r.push(15);
      return r;
    };
    img.onload = function(e) {
      var boxes, click, height, i, j, order, qh, qw, redraw, width, _i, _j;
      width = img.naturalWidth;
      height = img.naturalHeight;
      ctx.canvas.width = width;
      ctx.canvas.height = height;
      ctx.drawImage(img, 0, 0);
      qw = Math.floor(width / 4);
      qh = Math.floor(height / 4);
      order = shuffle();
      boxes = [];
      for (i = _i = 0; _i <= 3; i = ++_i) {
        for (j = _j = 0; _j <= 3; j = ++_j) {
          boxes.push(ctx.getImageData(j * qw, i * qh, qw, qh));
        }
      }
      redraw = function(e) {
        var x, y, _k, _l;
        ctx.fillStyle = "#293134";
        ctx.fillRect(0, 0, width, height);
        for (i = _k = 0; _k <= 15; i = ++_k) {
          x = i % 4;
          y = Math.floor(i / 4);
          if (order[i] !== 15) {
            ctx.putImageData(boxes[order[i]], x * qw, y * qh);
          }
        }
        ctx.lineWidth = 2;
        ctx.strokeStyle = "#293134";
        for (i = _l = 0; _l <= 4; i = ++_l) {
          ctx.moveTo(i * qw, 0);
          ctx.lineTo(i * qw, height);
          ctx.moveTo(0, i * qh);
          ctx.lineTo(width, i * qh);
        }
        return ctx.stroke();
      };
      click = function(e) {
        var cx, cy, ei, ex, ey, x, y, _k, _len, _ref, _ref1, _ref2, _results;
        x = Math.floor((e.pageX - e.target.offsetLeft) / qw);
        y = Math.floor((e.pageY - e.target.offsetTop) / qh);
        ei = order.indexOf(15);
        ex = ei % 4;
        ey = Math.floor(ei / 4);
        _ref = [[ex + 1, ey], [ex - 1, ey], [ex, ey + 1], [ex, ey - 1]];
        _results = [];
        for (_k = 0, _len = _ref.length; _k < _len; _k++) {
          _ref1 = _ref[_k], cx = _ref1[0], cy = _ref1[1];
          if (cx === x && cy === y) {
            i = x + y * 4;
            _ref2 = [order[ei], order[i]], order[i] = _ref2[0], order[ei] = _ref2[1];
            redraw();
            if ([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15].every(function(i) {
              return order[i] === i;
            })) {
              win();
            }
            break;
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      };
      $("#area").on("click", click);
      return redraw();
    };
    files = ["Cabo_Espichel,_Portugal,_2012-08-18,_DD_08.png", "Furnadoia_de_Seceda_y_Resciesa.png", "Geirangerfjord_from_Ørnesvingen,_2013_June.png"];
    return img.src = files[Math.min(files.length - 1, Math.floor(Math.random() * files.length))];
  });

}).call(this);
